### ISSUE TITLE
NumberInput arrow icons not flexible.

### ISSUE THREAD

**Issue by amirhossein-fzl** [iced-rs/iced_aw#126] opened 2023-05-31 16:03 UTC
The image shows that the input arrows are not proportional to the input size and unfortunately, it cannot be customized. Please solve the problem. Thank you 🙏

![image](https://github.com/iced-rs/iced_aw/assets/53816722/a310808b-171c-4818-9a24-6f7146784d8f)

and codes ...

```rust
fn view(&self) -> Element<'_, Self::Message> {
    container(
        column![
            text("Password Generator").size(24).width(Length::Fill),
            column![
                text("Length: "),
                NumberInput::new(self.length, 50, Message::ChangeLength)
                    .style(NumberInputStyles::Default),
            ]
            .spacing(8),
            row![
                text_input(
                    &String::from("password"),
                    &self.password,
                    Message::PassChange
                ),
                button("Copy").on_press(Message::Copy),
            ],
            button("Generate").on_press(Message::Generate)
        ]
        .spacing(30),
    )
    .center_x()
    .center_y()
    .width(Length::Fill)
    .height(Length::Fill)
    .padding(10)
    .into()
}
```

**Comment by genusistimelord** [comment] 2023-05-31 18:09
![image](https://github.com/iced-rs/iced_aw/assets/1034709/ea672c7d-0996-454f-8e1e-4903dce3f788)

what exactly are you changing the cause this? as the above is what I got with just coping your code and using the default theme etc.

**Comment by genusistimelord** [comment] 2023-06-14 19:12
Ok i have figured out the cause of this. IT has to do with the default Text size being set. I will try to figure out how to fix the issue.

**Comment by amirhossein-fzl** [comment] 2023-06-16 14:06
> Ok i have figured out the cause of this. IT has to do with the default Text size being set. I will try to figure out how to fix the issue.

I changed my default desktop font and because of that, nothing aligns. These problems should not exist ...

**Comment by genusistimelord** [comment] 2023-06-16 14:27
yeah its due to a calculation inside the layout. it doesnt take into consideration different sizes of fonts. we will get this fixed once we figure out the correct way.

**Comment by amirhossein-fzl** [comment] 2023-06-17 10:03
> yeah its due to a calculation inside the layout. it doesnt take into consideration different sizes of fonts. we will get this fixed once we figure out the correct way.

Also this problem:
https://github.com/iced-rs/iced/issues/1887

**Closed** 2023-08-04 15:13 UTC
