### ISSUE TITLE
Tabs widget only works when at top level of widget hierarchy

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [iced-rs/iced_aw#155] opened 2023-07-18 16:27 UTC
I would like to have a sub-area of my app's UI as a set of tabs with content. I cannot get this to work, as the tab title areas expand to take all space. It only seems to work when Tabs widget is at the highest level of the widget tree, under Application.

I have stripped down the example/tabs example code to be minimal, but implement Application instead of Sandbox (to mirror my own app).

Then this code in main.rs works:

```
    fn view(&self) -> Element<'_, Self::Message> {
        Tabs::new(self.active_tab, Message::TabSelected)
            .push(self.login_tab.tab_label(), self.login_tab.view())
            .push(self.ferris_tab.tab_label(), self.ferris_tab.view())
            .into()
    }
```

And two tabs are shown with simple text titles and the content of each tab is visible.
(I have hacked the content so it's different)
screenshot:
<img width="1028" alt="Screenshot 2023-07-18 at 6 20 57 PM" src="https://github.com/iced-rs/iced_aw/assets/5529132/123a777e-5970-42e4-88a5-ee01477004e7">

and this code, placing Tabs inside a container fails:
(placing in _just_ a Column, with no container also fails)

```
    fn view(&self) -> Element<'_, Self::Message> {
        let tabs = Tabs::new(self.active_tab, Message::TabSelected)
            .push(self.login_tab.tab_label(), self.login_tab.view())
            .push(self.ferris_tab.tab_label(), self.ferris_tab.view());

        let column = Column::new().push(tabs);

        container(column)
            .into()
    }
```

The failure is that the Tab title area height expands to fill the entire widget and no content is visible.

screenshot:
<img width="1027" alt="Screenshot 2023-07-18 at 6 20 27 PM" src="https://github.com/iced-rs/iced_aw/assets/5529132/ae357d63-7d78-49d8-a389-0de758d92571">

i.e. the appearance of the Tabs widget changes depends on the parent.

Is there any way to achieve what I want, only a part of my UI to have tabs?

**Comment by andrewdavidmackenzie** [comment] 2023-07-18 16:47
I think I tried that (but will try again), and would that explain why they are OK when Tabs at the top level?

**Comment by andrewdavidmackenzie** [comment] 2023-07-18 16:52
The issue is with the TabLabel height, and I don't see how to set it's height.
In the screenshot you can see that the height of the text within it is fine.

```
        Tabs::new(self.active_tab, Message::TabSelected)
            .push(self.stdout_tab.tab_label(), self.stdout_tab.view())
            .push(self.stderr_tab.tab_label(), self.stderr_tab.view())
            .into()
```

**Comment by andrewdavidmackenzie** [comment] 2023-07-18 20:44
Pushed this small repo to help reproduce it

https://github.com/andrewdavidmackenzie/tabs/blob/master/src/main.rs#L56

just comment / uncomment the two implementations of view()

**Comment by genusistimelord** [comment] 2023-07-18 22:52
OK thank you for the help. I will try to get this fixed in the new release when i get to the tabs =].

**Comment by andrewdavidmackenzie** [comment] 2023-07-27 07:14
Let me know if I can help in any way. I did a bunch of other stuff, and adding tabs into my app is now near the top of my todo list :-)

**Comment by genusistimelord** [comment] 2023-07-27 11:44
Yeah I was able to fix some other tab issues not sure if the newest fixes this issue just yet. Feel free to take a look at the Iced_new branch as this is where all the newest changes are being pushed for the next iced.

**Comment by andrewdavidmackenzie** [comment] 2023-07-27 13:16
"New_iced" branch :-) 

Has the API changed?

```
   Compiling tabs v0.1.0 (/Users/andrew/workspace/tabs)
error[E0277]: expected a `Fn<(_,)>` closure, found `usize`
  --> src/main.rs:58:30
   |
58 |         let tabs = Tabs::new(self.active_tab, Message::TabSelected)
   |                    --------- ^^^^^^^^^^^^^^^ expected an `Fn<(_,)>` closure, found `usize`
   |                    |
   |                    required by a bound introduced by this call
   |
   = help: the trait `Fn<(_,)>` is not implemented for `usize`
note: required by a bound in `Tabs::<'a, Message, TabId, Renderer>::new`
  --> /Users/andrew/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/5b2c65d/src/native/tabs.rs:94:22
   |
92 |     pub fn new<F>(on_select: F) -> Self
   |            --- required by a bound in this associated function
93 |     where
94 |         F: 'static + Fn(TabId) -> Message,
   |                      ^^^^^^^^^^^^^^^^^^^^ required by this bound in `Tabs::<'a, Message, TabId, Renderer>::new`

error[E0061]: this function takes 1 argument but 2 arguments were supplied
  --> src/main.rs:58:20
   |
58 |         let tabs = Tabs::new(self.active_tab, Message::TabSelected)
   |                    ^^^^^^^^^                ----------------------
   |                                             | |
   |                                             | unexpected argument of type `fn(usize) -> Message {Message::TabSelected}`
   |                                             help: remove the extra argument
   |
note: associated function defined here
  --> /Users/andrew/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/5b2c65d/src/native/tabs.rs:92:12
   |
92 |     pub fn new<F>(on_select: F) -> Self
   |            ^^^

error[E0277]: the trait bound `TabLabel: Eq` is not satisfied
  --> src/main.rs:58:20
   |
58 |         let tabs = Tabs::new(self.active_tab, Message::TabSelected)
   |                    ^^^^^^^^^ the trait `Eq` is not implemented for `TabLabel`
   |
note: required by a bound in `Tabs::<'a, Message, TabId, Renderer>::new`
  --> /Users/andrew/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/5b2c65d/src/native/tabs.rs:82:12
   |
82 |     TabId: Eq + Clone,
   |            ^^ required by this bound in `Tabs::<'a, Message, TabId, Renderer>::new`
...
92 |     pub fn new<F>(on_select: F) -> Self
   |            --- required by a bound in this associated function

error[E0277]: the trait bound `TabLabel: Eq` is not satisfied
  --> src/main.rs:58:20
   |
58 |         let tabs = Tabs::new(self.active_tab, Message::TabSelected)
   |                    ^^^^ the trait `Eq` is not implemented for `TabLabel`
   |
note: required by a bound in `Tabs`
  --> /Users/andrew/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/5b2c65d/src/native/tabs.rs:62:12
   |
58 | pub struct Tabs<'a, Message, TabId, Renderer = crate::Renderer>
   |            ---- required by a bound in this struct
...
62 |     TabId: Eq + Clone,
   |            ^^ required by this bound in `Tabs`

error[E0277]: the trait bound `TabLabel: Eq` is not satisfied
   --> src/main.rs:59:14
    |
59  |             .push(self.login_tab.tab_label(), self.login_tab.view())
    |              ^^^^ the trait `Eq` is not implemented for `TabLabel`
    |
note: required by a bound in `Tabs::<'a, Message, TabId, Renderer>::push`
   --> /Users/andrew/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/5b2c65d/src/native/tabs.rs:82:12
    |
82  |     TabId: Eq + Clone,
    |            ^^ required by this bound in `Tabs::<'a, Message, TabId, Renderer>::push`
...
262 |     pub fn push<E>(mut self, id: TabId, tab_label: TabLabel, element: E) -> Self
    |            ---- required by a bound in this associated function

error[E0061]: this method takes 3 arguments but 2 arguments were supplied
   --> src/main.rs:59:14
    |
59  |             .push(self.login_tab.tab_label(), self.login_tab.view())
    |              ^^^^                             --------------------- an argument of type `TabLabel` is missing
    |
note: method defined here
   --> /Users/andrew/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/5b2c65d/src/native/tabs.rs:262:12
    |
262 |     pub fn push<E>(mut self, id: TabId, tab_label: TabLabel, element: E) -> Self
    |            ^^^^
help: provide the argument
    |
59  |             .push(self.login_tab.tab_label(), /* TabLabel */, self.login_tab.view())
    |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

error[E0599]: the method `push` exists for struct `Tabs<'_, _, TabLabel, _>`, but its trait bounds were not satisfied
  --> src/main.rs:60:14
   |
58 |           let tabs = Tabs::new(self.active_tab, Message::TabSelected)
   |  ____________________-
59 | |             .push(self.login_tab.tab_label(), self.login_tab.view())
60 | |             .push(self.ferris_tab.tab_label(), self.ferris_tab.view());
   | |             -^^^^ method cannot be called on `Tabs<'_, _, TabLabel, _>` due to unsatisfied trait bounds
   | |_____________|
   | 
   |
  ::: /Users/andrew/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/5b2c65d/src/native/tab_bar/tab_label.rs:9:1
   |
9  |   pub enum TabLabel {
   |   -----------------
   |   |
   |   doesn't satisfy `TabLabel: Eq`
   |   doesn't satisfy `TabLabel: PartialEq`
   |
   = note: the following trait bounds were not satisfied:
           `TabLabel: Eq`
           `TabLabel: PartialEq`
           which is required by `TabLabel: Eq`

Some errors have detailed explanations: E0061, E0277, E0599.
For more information about an error, try `rustc --explain E0061`.
error: could not compile `tabs` (bin "tabs") due to 7 previous errors
```

**Comment by genusistimelord** [comment] 2023-07-27 13:18
yeah you want Tabs::new_with for that.

**Comment by andrewdavidmackenzie** [comment] 2023-07-27 13:58
OK, I think I'll wait for this to be merged, can't be yak-shaving this right now.

**Comment by genusistimelord** [comment] 2023-07-27 14:23
sorry yeah with tabs is correct. I am close to merging this as well.

**Comment by genusistimelord** [comment] 2023-07-27 15:06
Ok this has been merged now. Please take a look at main and see if you can pin point the cause. I do want to try and get this released around when Iced 0.10 is released tomorrow though.

**Comment by genusistimelord** [comment] 2023-07-28 14:26
the tabs example itself works just fine with no compile errors?
![image](https://github.com/iced-rs/iced_aw/assets/1034709/033a02c9-3c61-4d7a-9064-af60ca1fcc7a)

**Comment by genusistimelord** [comment] 2023-07-31 17:50
please give it a try with the newest main push

**Comment by andrewdavidmackenzie** [comment] 2023-07-31 19:46
Yeh!! That works now!!!

<img width="1029" alt="Screenshot 2023-07-31 at 9 45 50 PM" src="https://github.com/iced-rs/iced_aw/assets/5529132/d7d80772-b064-4531-bcac-15f723dc1e80">

**Comment by andrewdavidmackenzie** [comment] 2023-07-31 19:46
You can close this issue as fixed when you want, and I will look out for a new release.
Thanks for your hard work!

**Comment by genusistimelord** [comment] 2023-07-31 19:48
fixed

**Closed by genusistimelord** 2023-07-31 19:48 UTC

**Comment by andrewdavidmackenzie** [comment] 2023-08-02 09:15
I'm trying to update my real app to use this now, and running into issues due to API changes.

It seems a tab ID is no longer the "Id" type (no need for Lazy, etc - good).
This seems to be just a reference and I just use an enum for my tab ids, like in the example.

But I use scrollable::snap_to() (https://docs.rs/iced/latest/iced/widget/scrollable/fn.snap_to.html) to snap to some content in a tab, and that still requires an `Id` type....

How best to handle this, and get a unique Id I can use with scrollable?

**Comment by genusistimelord** [comment] 2023-08-02 11:34
that method is to only snap the scroll-able itself via its ID to a given percentage range.  it is not to attach to other widgets. Only widgets that use Operations get unique Id's.
