### ISSUE TITLE
Modal example fails to compile

### ISSUE THREAD

**Issue by LeSnake04** [iced-rs/iced_aw#76] opened 2023-01-02 13:22 UTC
Taken from the official example in the Modal docstring

```rs
let modal = Modal::new(true, Text::new("Underlay"), || Text::new("Overlay").into())
    .backdrop(Message::AddPaths);
```

This fails to compile with the following error:
```
error[E0283]: type annotations needed
   --> renameplus_gui/src/gui.rs:100:15
    |
100 |         let modal = Modal::new(true, Text::new("Underlay"), || Text::new("Overlay").into())
    |                     ^^^^^^^^^^ cannot infer type of the type parameter `U` declared on the associated function `new`
    |
    = note: cannot satisfy `_: iced_aw::modal::StyleSheet`
    = help: the trait `iced_aw::modal::StyleSheet` is implemented for `iced::Theme`
note: required by a bound in `iced_aw::native::Modal::<'a, Content, Message, Renderer>::new`
   --> /home/USER/.cargo/git/checkouts/iced_aw-d8617147b960a6c7/193e3bd/src/native/modal.rs:63:22
    |
63  |     Renderer::Theme: StyleSheet,
    |                      ^^^^^^^^^^ required by this bound in `Modal::<'a, Content, Message, Renderer>::new`
help: consider specifying the generic argument
    |
100 |         let modal = Modal::new::<iced_native::widget::Text<'_, iced_graphics::renderer::Renderer<Backend, Theme>>>(true, Text::new("Underlay"), || Text::new("Overlay").into())
    |                               ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```

**Comment by genusistimelord** [comment] 2023-01-30 15:25
not sure there is much we can do about this issue. I will need to look into it more to find out. I suspect it is an issue with all the new generic requirements.

**Comment by genusistimelord** [comment] 2023-05-08 19:48
I could not recreate this issue. So I would suggest trying this with the Main branch of iced_aw and with the latest iced. As placing it like you showed above does not break compiling.  So I am closing this issue since it can not be reproduced.

**Closed by genusistimelord** 2023-05-08 19:48 UTC
